site_name: EDAC Docs

theme: readthedocs

google_analytics:
  - UA-208228992-2
  - auto

extra_javascript: 
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math

plugins:
  - search